# Generated by Django 5.0 on 2024-01-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind',
        ),
    ]
