# Generated by Django 5.0 on 2024-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.TextField(default='everything', max_length=100),
        ),
    ]
