# Generated by Django 5.0 on 2024-01-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(choices=[('bbc_news', 'BBC News'), ('cnn', 'CNN News'), ('nbc_news', 'NBC News'), ('abc_news', 'ABC News'), ('the-washington-post', 'The Washington Post'), ('espn', 'ESPN'), ('associated-press', 'Associated Press')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.TextField(default='general', max_length=100),
        ),
    ]
