# Generated by Django 5.0 on 2024-02-02 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_news_source_alter_news_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
