# Generated by Django 5.0 on 2024-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_task_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
