# Generated by Django 5.0 on 2024-02-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.TextField(max_length=100),
        ),
    ]
