# Generated by Django 5.0 on 2024-02-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
