# Generated by Django 5.0 on 2024-02-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_news_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'start_time']},
        ),
    ]
