# Generated by Django 5.0 on 2024-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_mirrordisplay_display_alter_news_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.TextField(default='Technology', max_length=100, null=True),
        ),
    ]
