# Generated by Django 5.0 on 2024-02-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_news_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirrordisplay',
            name='display',
            field=models.CharField(choices=[('default', 'Default'), ('display2', 'Display 2'), ('display3', 'Display 3'), ('display4', 'Display 4'), ('display5', 'Display 5'), ('display6', 'Display 6')], default='Default', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(choices=[('bbc_news', 'BBC News'), ('cnn', 'CNN News'), ('nbc_news', 'NBC News'), ('abc_news', 'ABC News'), ('the-washington-post', 'The Washington Post'), ('espn', 'ESPN'), ('associated-press', 'Associated Press')], default='BBC News', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.TextField(default='Technology', max_length=100),
        ),
    ]
