# Generated by Django 5.0 on 2024-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_mirrordisplay_display_alter_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirrordisplay',
            name='display',
            field=models.CharField(choices=[('Default', 'Default'), ('Display 2', 'Display 2'), ('Display 3', 'Display 3'), ('Display 4', 'Display 4'), ('Display 5', 'Display 5'), ('Display 6', 'Display 6')], default='default', max_length=50),
        ),
    ]
